name: Build and Test Subversion
on:
  push:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      url:
        default: https://svn.apache.org/repos/asf/subversion/trunk
        type: string
        description: URL to checkout Subvesion from
      revision:
        default: HEAD
        type: string
        description: Revision to checkout Subvesion from

jobs:
  windows-vcnet:
    runs-on: windows-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
              core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
              core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install dependecies
        run: C:\vcpkg\vcpkg.exe install apr apr-util expat zlib --triplet x64-windows-release

      - name: Checkout
        run: svn checkout ${{ inputs.url }} --revision ${{ inputs.revision }} svn

      - name: gen-make
        run: |
          $deps = C:\vcpkg\installed\x64-windows-release
          python ./svn/gen-make.py `
            -t vcpnet --vsnet-version=15.0 `
            --with-apr=$deps `
            --with-aprutil=$deps `
            --with-expat=$deps `
            --with-zlib=$deps

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: MSBuild.exe .\subversion_vcnet.sln
