name: Build and Test Subversion
on:
  push:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      url:
        default: https://svn.apache.org/repos/asf/subversion/trunk
        type: string
        description: URL to checkout Subvesion from
      revision:
        default: HEAD
        type: string
        description: Revision to checkout Subvesion from

jobs:
  linux-make:
    runs-on: ubuntu-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: svn-ci

      - name: Checkout
        run: |
          $url = "${{ inputs.url }}"
          if ($url -eq "") {
            $url = "https://svn.apache.org/repos/asf/subversion/trunk"
          }

          $revision = "${{ inputs.revision }}"
          if ($revision -eq "") {
            $revision = "HEAD"
          }

          svn checkout $url --revision $revision svn

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
              core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
              core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install dependecies
        run: |
          /usr/local/share/vcpkg/vcpkg `
            install apr apr-util expat zlib `
            --triplet x64-linux-release

      - name: Download and extract sqlite amalgamation
        run: |
          Invoke-WebRequest `
            -Uri https://sqlite.org/2024/sqlite-amalgamation-3460000.zip `
            -OutFile sqlite-amalgamation.zip

          Expand-Archive `
            -Path .\sqlite-amalgamation.zip `
            -DestinationPath .

      - name: autogen.sh
        working-directory: ./svn
        run: sh ./autogen.sh

      - name: configure
        working-directory: ./svn
        run: |
          $deps = "/usr/local/share/vcpkg/installed/x64-linux-release"

          ls $deps -r

          ./configure `
            --with-apr=$deps `
            --with-apr-util=$deps `
            --with-zlib=$deps `
            --with-sqlite=../sqlite-amalgamation-3460000

      - name: Build
        working-directory: ./svn
        run: make

  windows-vcnet:
    runs-on: windows-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: svn-ci

      - name: Checkout
        run: |
          $url = "${{ inputs.url }}"
          if ($url -eq "") {
            $url = "https://svn.apache.org/repos/asf/subversion/trunk"
          }

          $revision = "${{ inputs.revision }}"
          if ($revision -eq "") {
            $revision = "HEAD"
          }

          svn checkout $url --revision $revision svn

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
              core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
              core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install dependecies
        run: |
          C:\vcpkg\vcpkg.exe `
            install apr apr-util expat zlib `
            --overlay-triplets ./svn-ci/triplets `
            --triplet x64-svn-windows

      - name: Download and extract sqlite amalgamation
        run: |
          Invoke-WebRequest `
            -Uri https://sqlite.org/2024/sqlite-amalgamation-3460000.zip `
            -OutFile sqlite-amalgamation.zip

          Expand-Archive `
            -Path .\sqlite-amalgamation.zip `
            -DestinationPath .

      - name: gen-make
        working-directory: svn
        run: |
          $deps = "C:\vcpkg\installed\x64-svn-windows"
          python ./gen-make.py `
            -t vcproj --vsnet-version=2022 `
            --with-apr=$deps `
            --with-apr-util=$deps `
            --with-zlib=$deps `
            --with-sqlite=../sqlite-amalgamation-3460000

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
           MSBuild.exe .\svn\subversion_vcnet.sln `
            /t:__ALL_TESTS__ `
            /p:Platform=x64 `
            /v:minimal

      - name: Test
        working-directory: svn
        run: |
          python ./win-tests.py --parallel
