name: Build and Test Subversion
on:
  push:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      url:
        default: https://svn.apache.org/repos/asf/subversion/trunk
        type: string
        description: URL to checkout Subvesion from
      revision:
        default: HEAD
        type: string
        description: Revision to checkout Subvesion from

jobs:
  windows-vcnet:
    runs-on: windows-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
              core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
              core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install dependecies
        run: C:\vcpkg\vcpkg.exe install apr apr-util expat zlib --triplet x64-windows-release

      - name: Download and extract sqlite amalgamation
        run: |
          Invoke-WebRequest `
            -Uri https://sqlite.org/2024/sqlite-amalgamation-3460000.zip `
            -OutFile sqlite-amalgamation.zip

          Expand-Archive `
            -Path .\sqlite-amalgamation.zip `
            -DestinationPath .

      - name: Checkout
        run: |
          $url = "${{ inputs.url }}"
          if ($url -eq "") {
            $url = "https://svn.apache.org/repos/asf/subversion/trunk"
          }

          $revision = "${{ inputs.revision }}"
          if ($revision -eq "") {
            $revision = "HEAD"
          }

          svn checkout $url --revision $revision svn

      - name: gen-make
        working-directory: svn
        run: |
          $deps = "C:\vcpkg\installed\x64-windows-release"
          python ./gen-make.py `
            -t vcproj --vsnet-version=2022 `
            --with-apr=$deps `
            --with-apr-util=$deps `
            --with-zlib=$deps `
            --with-sqlite=../sqlite-amalgamation-3460000

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: MSBuild.exe .\subversion_vcnet.sln
